Fix Actions (#1)

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -2,7 +2,7 @@ name: Docker
 
 on:
   schedule:
-    - cron: '0 0 * * 0'  # Runs every sunday
+    - cron: '0 0 * * 0'  # Runs every Sunday
     
   workflow_dispatch:  # Allow manual triggering
   
@@ -25,6 +25,13 @@ jobs:
       - name: Checkout this repository
         uses: actions/checkout@v4
 
+      - name: Restore commit cache
+        uses: actions/cache@v3
+        with:
+          path: latest_commit.txt
+          key: latest-commit-${{ env.TARGET_REPO }}
+          restore-keys: latest-commit-
+
       - name: Get latest commit from target repo
         id: get_latest_commit
         run: |
@@ -43,18 +50,22 @@ jobs:
           echo "Latest commit: $LATEST_COMMIT"
           if [ "$LATEST_COMMIT" == "$PREV_COMMIT" ]; then
             echo "No new commit. Exiting..."
+            echo "changed=false" >> $GITHUB_OUTPUT
             exit 0
           fi
           echo "$LATEST_COMMIT" > latest_commit.txt
+          echo "changed=true" >> $GITHUB_OUTPUT
 
       - name: Commit change detected, proceeding with build
         if: steps.check_commit.outputs.changed == 'true'
         run: echo "New commit detected. Running the build..."
 
       - name: Set up Docker Buildx
+        if: steps.check_commit.outputs.changed == 'true'
         uses: docker/setup-buildx-action@v3
 
       - name: Log into registry ${{ env.REGISTRY }}
+        if: steps.check_commit.outputs.changed == 'true'
         uses: docker/login-action@v3
         with:
           registry: ${{ env.REGISTRY }}
@@ -62,12 +73,15 @@ jobs:
           password: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Extract Docker metadata
+        if: steps.check_commit.outputs.changed == 'true'
         id: meta
         uses: docker/metadata-action@v5
         with:
           images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
 
       - name: Build and push Docker image
+        if: steps.check_commit.outputs.changed == 'true'
+        id: build-and-push  # Add an ID to capture outputs
         uses: docker/build-push-action@v5
         with:
           context: .
@@ -78,7 +92,20 @@ jobs:
           # not cache cache-to: type=gha,mode=max
 
       - name: Sign the Docker image
+        if: steps.check_commit.outputs.changed == 'true'
         env:
           TAGS: ${{ steps.meta.outputs.tags }}
           DIGEST: ${{ steps.build-and-push.outputs.digest }}
-        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
+        run: |
+          if [ -z "${DIGEST}" ]; then
+            echo "Error: DIGEST is empty."
+            exit 1
+          fi
+          echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
+
+      - name: Cache the latest commit file
+        if: steps.check_commit.outputs.changed == 'true'
+        uses: actions/cache@v3
+        with:
+          path: latest_commit.txt
+          key: latest-commit-${{ env.TARGET_REPO }}
